# Copyright (c) 2016 Kazumasa Kohtaka. All rights reserved.
# This file is available under the MIT license.

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    update_cache: yes

- name: Install ca-certificates
  apt:
    name: ca-certificates
    update_cache: yes

- name: Install GPG key for Docker
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Add Docker APT repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    state: present

- name: Install Docker APT package
  apt:
    name: docker-engine
    update_cache: yes

- name: Enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
