# Copyright (c) 2016 Kazumasa Kohtaka. All rights reserved.
# This file is available under the MIT license.

- name: install postgres environment file
  template:
    src: postgres.env.j2
    dest: /etc/default/postgres
    owner: root
    group: root
    mode: 0644
  notify: restart postgres service

- name: install postgres service
  template:
    src: postgres.service.j2
    dest: /etc/systemd/system/postgres.service
    owner: root
    group: root
    mode: 0644

- name: ensure postgres service started
  systemd:
    name: postgres
    state: started
    daemon_reload: yes
